### PR TITLE
Unicode 10.0

### PR DESCRIPTION
**Pull request by lemzwerg**
A necessary fix for a typo.

### CODE REVIEW

**Comment by Pomax** [comment]
cheers. I'll try to get a new copy on CTAN today.

**Comment by lemzwerg** [comment]
Thanks a lot!

**Comment by Pomax** [comment]
v2.3.1 should be on CTAN whenever it goes through.

**Comment by lemzwerg** [comment]
Hmm, ucharclasses hasn't been announced yet on the ctan mailing list, nor is it available from CTAN – are you sure your upload was successful?  I've seen various CTAN announcement recently (from the German team I guess), so the responsible persons are not on vacation...

**Comment by Pomax** [comment]
yeah there were some issues that CTAN flagged that I need to fix around versioning (git somehow didn't get the release tag) and obsolete links for pointing to CTAN's public domain license details. I'll try to get a reversioned 2.3.0 (rather than 2.3.1, since we're minor bumping from 2..2..x) up today

**Comment by Pomax** [comment]
I've reuploaded 2.3.0 now that its git tag is correct, and the readme, sty, and tex files have the correct date and links to the PD license.

**Comment by lemzwerg** [comment]
Thanks a lot for your efforts!

**Comment by Pomax** [comment]
And you for adding Unicode 10 support!

**Pull request merged**
